[cfg]
base = "rss/"

# Quds News - عربي
[source001]
name = "qudsn_ar.xml"
url = "https://tg.i-c-a.su/rss/QudsN"
max = "20"
action = "auto->ar"
chat = "@Qassamcircler"

# Quds News - إنجليزي
[source002]
name = "qudsn_en.xml"
url = "https://tg.i-c-a.su/rss/QudsN"
max = "20"
action = "auto->en"
chat = "@Qassamcircler"

# Quds News - فارسي
[source003]
name = "qudsn_fa.xml"
url = "https://tg.i-c-a.su/rss/QudsN"
max = "20"
action = "auto->fa"
chat = "@Qassamcircler"


# 🔥 الجزيرة (بديل الجزيرة مباشر)
[source004]
name = "aljazeera_ar.xml"
url = "https://tg.i-c-a.su/rss/ajNews"
max = "20"
action = "auto->ar"
chat = "@Qassamcircler"

# 🔥 الميادين
[source005]
name = "almayadeen_ar.xml"
url = "https://tg.i-c-a.su/rss/almayadeen"
max = "20"
action = "auto->ar"
chat = "@Qassamcircler"
