[cfg]
base = "rss/"

# ======================
# 🔴 الجزيرة
# ======================

# عربي
[source001]
name = "aja_ar.xml"
url = "https://tg.i-c-a.su/rss/AjaNews"
max = "20"
action = "auto->ar"
chat = "@Qassamcircler"

# إنجليزي
[source002]
name = "aja_en.xml"
url = "https://tg.i-c-a.su/rss/AjaNews"
max = "20"
action = "auto->en"
chat = "@Qassamcircler"

# فارسي
[source003]
name = "aja_fa.xml"
url = "https://tg.i-c-a.su/rss/AjaNews"
max = "20"
action = "auto->fa"
chat = "@Qassamcircler"

# ======================
# 🔴 الميادين
# ======================

# عربي
[source004]
name = "mayadeen_ar.xml"
url = "https://tg.i-c-a.su/rss/almayadeen"
max = "20"
action = "auto->ar"
chat = "@Qassamcircler"

# إنجليزي
[source005]
name = "mayadeen_en.xml"
url = "https://tg.i-c-a.su/rss/almayadeen"
max = "20"
action = "auto->en"
chat = "@Qassamcircler"

# فارسي
[source006]
name = "mayadeen_fa.xml"
url = "https://tg.i-c-a.su/rss/almayadeen"
max = "20"
action = "auto->fa"
chat = "@Qassamcircler"
