[cfg]
base = "rss/"

# Aja News - عربي
[source001]
name = "ajanews_ar.xml"
url = "https://tg.i-c-a.su/rss/AjaNews"
max = "20"
action = "auto->ar"
chat = "@Qassamcircler"

# Aja News - إنجليزي
[source002]
name = "ajanews_en.xml"
url = "https://tg.i-c-a.su/rss/AjaNews"
max = "20"
action = "auto->en"
chat = "@Qassamcircler"

# Aja News - فارسي
[source003]
name = "ajanews_fa.xml"
url = "https://tg.i-c-a.su/rss/AjaNews"
max = "20"
action = "auto->fa"
chat = "@Qassamcircler"
