name: RSS Telegram Bot

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/upload-artifact@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run bot
        run: python main.py
